arb-dir: l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: l10n/untranslated_messages.txt
synthetic-package: false
